package domain

import (
	"errors"
	"testing"
)

// Golden exaustivo de Validate: 8 tipos x 6 indices x 5 modalidades. Alem do
// erro, congela os defaults que Validate aplica no proprio request (ele muta o
// receptor), porque esses defaults fazem parte do contrato. Serve de rede para
// a conversao do switch em tabela de regras.
//
// Uma unica linha mudou de proposito na conversao: para LCI e LCA com indice
// invalido e modalidade vazia, o codigo antigo gravava Modality="POS" antes de
// validar o indice, deixando essa mutacao para tras ao rejeitar com
// ErrInvalidIndex. A versao em tabela valida o indice primeiro e nao escreve
// nada. O erro devolvido e o mesmo, e a mutacao era inobservavel: Analyze
// recebe o request por valor e o handler guarda a sua propria copia em Input.
func TestValidateGolden(t *testing.T) {
	casos := []struct {
		tipo            string
		index           string
		modalidade      string
		erro            error
		indexFinal      string
		modalidadeFinal string
	}{
		{"CDB", "", "", nil, "CDI", "POS"},
		{"CDB", "", "POS", nil, "CDI", "POS"},
		{"CDB", "", "PRE", ErrInvalidModality, "CDI", "PRE"},
		{"CDB", "", "IPCA", ErrInvalidModality, "CDI", "IPCA"},
		{"CDB", "", "XYZ", ErrInvalidModality, "CDI", "XYZ"},
		{"CDB", "CDI", "", nil, "CDI", "POS"},
		{"CDB", "CDI", "POS", nil, "CDI", "POS"},
		{"CDB", "CDI", "PRE", ErrInvalidModality, "CDI", "PRE"},
		{"CDB", "CDI", "IPCA", ErrInvalidModality, "CDI", "IPCA"},
		{"CDB", "CDI", "XYZ", ErrInvalidModality, "CDI", "XYZ"},
		{"CDB", "PREFIXADO", "", ErrInvalidIndex, "PREFIXADO", ""},
		{"CDB", "PREFIXADO", "POS", ErrInvalidIndex, "PREFIXADO", "POS"},
		{"CDB", "PREFIXADO", "PRE", ErrInvalidIndex, "PREFIXADO", "PRE"},
		{"CDB", "PREFIXADO", "IPCA", ErrInvalidIndex, "PREFIXADO", "IPCA"},
		{"CDB", "PREFIXADO", "XYZ", ErrInvalidIndex, "PREFIXADO", "XYZ"},
		{"CDB", "SELIC", "", ErrInvalidIndex, "SELIC", ""},
		{"CDB", "SELIC", "POS", ErrInvalidIndex, "SELIC", "POS"},
		{"CDB", "SELIC", "PRE", ErrInvalidIndex, "SELIC", "PRE"},
		{"CDB", "SELIC", "IPCA", ErrInvalidIndex, "SELIC", "IPCA"},
		{"CDB", "SELIC", "XYZ", ErrInvalidIndex, "SELIC", "XYZ"},
		{"CDB", "IPCA", "", ErrInvalidIndex, "IPCA", ""},
		{"CDB", "IPCA", "POS", ErrInvalidIndex, "IPCA", "POS"},
		{"CDB", "IPCA", "PRE", ErrInvalidIndex, "IPCA", "PRE"},
		{"CDB", "IPCA", "IPCA", ErrInvalidIndex, "IPCA", "IPCA"},
		{"CDB", "IPCA", "XYZ", ErrInvalidIndex, "IPCA", "XYZ"},
		{"CDB", "XYZ", "", ErrInvalidIndex, "XYZ", ""},
		{"CDB", "XYZ", "POS", ErrInvalidIndex, "XYZ", "POS"},
		{"CDB", "XYZ", "PRE", ErrInvalidIndex, "XYZ", "PRE"},
		{"CDB", "XYZ", "IPCA", ErrInvalidIndex, "XYZ", "IPCA"},
		{"CDB", "XYZ", "XYZ", ErrInvalidIndex, "XYZ", "XYZ"},
		{"LCI", "", "", nil, "CDI", "POS"},
		{"LCI", "", "POS", nil, "CDI", "POS"},
		{"LCI", "", "PRE", ErrInvalidModality, "CDI", "PRE"},
		{"LCI", "", "IPCA", ErrInvalidModality, "CDI", "IPCA"},
		{"LCI", "", "XYZ", ErrInvalidModality, "CDI", "XYZ"},
		{"LCI", "CDI", "", nil, "CDI", "POS"},
		{"LCI", "CDI", "POS", nil, "CDI", "POS"},
		{"LCI", "CDI", "PRE", ErrInvalidModality, "CDI", "PRE"},
		{"LCI", "CDI", "IPCA", ErrInvalidModality, "CDI", "IPCA"},
		{"LCI", "CDI", "XYZ", ErrInvalidModality, "CDI", "XYZ"},
		{"LCI", "PREFIXADO", "", nil, "PREFIXADO", "PRE"},
		{"LCI", "PREFIXADO", "POS", ErrInvalidModality, "PREFIXADO", "POS"},
		{"LCI", "PREFIXADO", "PRE", nil, "PREFIXADO", "PRE"},
		{"LCI", "PREFIXADO", "IPCA", ErrInvalidModality, "PREFIXADO", "IPCA"},
		{"LCI", "PREFIXADO", "XYZ", ErrInvalidModality, "PREFIXADO", "XYZ"},
		{"LCI", "SELIC", "", ErrInvalidIndex, "SELIC", ""},
		{"LCI", "SELIC", "POS", ErrInvalidIndex, "SELIC", "POS"},
		{"LCI", "SELIC", "PRE", ErrInvalidIndex, "SELIC", "PRE"},
		{"LCI", "SELIC", "IPCA", ErrInvalidIndex, "SELIC", "IPCA"},
		{"LCI", "SELIC", "XYZ", ErrInvalidIndex, "SELIC", "XYZ"},
		{"LCI", "IPCA", "", ErrInvalidIndex, "IPCA", ""},
		{"LCI", "IPCA", "POS", ErrInvalidIndex, "IPCA", "POS"},
		{"LCI", "IPCA", "PRE", ErrInvalidIndex, "IPCA", "PRE"},
		{"LCI", "IPCA", "IPCA", ErrInvalidIndex, "IPCA", "IPCA"},
		{"LCI", "IPCA", "XYZ", ErrInvalidIndex, "IPCA", "XYZ"},
		{"LCI", "XYZ", "", ErrInvalidIndex, "XYZ", ""},
		{"LCI", "XYZ", "POS", ErrInvalidIndex, "XYZ", "POS"},
		{"LCI", "XYZ", "PRE", ErrInvalidIndex, "XYZ", "PRE"},
		{"LCI", "XYZ", "IPCA", ErrInvalidIndex, "XYZ", "IPCA"},
		{"LCI", "XYZ", "XYZ", ErrInvalidIndex, "XYZ", "XYZ"},
		{"LCA", "", "", nil, "CDI", "POS"},
		{"LCA", "", "POS", nil, "CDI", "POS"},
		{"LCA", "", "PRE", ErrInvalidModality, "CDI", "PRE"},
		{"LCA", "", "IPCA", ErrInvalidModality, "CDI", "IPCA"},
		{"LCA", "", "XYZ", ErrInvalidModality, "CDI", "XYZ"},
		{"LCA", "CDI", "", nil, "CDI", "POS"},
		{"LCA", "CDI", "POS", nil, "CDI", "POS"},
		{"LCA", "CDI", "PRE", ErrInvalidModality, "CDI", "PRE"},
		{"LCA", "CDI", "IPCA", ErrInvalidModality, "CDI", "IPCA"},
		{"LCA", "CDI", "XYZ", ErrInvalidModality, "CDI", "XYZ"},
		{"LCA", "PREFIXADO", "", nil, "PREFIXADO", "PRE"},
		{"LCA", "PREFIXADO", "POS", ErrInvalidModality, "PREFIXADO", "POS"},
		{"LCA", "PREFIXADO", "PRE", nil, "PREFIXADO", "PRE"},
		{"LCA", "PREFIXADO", "IPCA", ErrInvalidModality, "PREFIXADO", "IPCA"},
		{"LCA", "PREFIXADO", "XYZ", ErrInvalidModality, "PREFIXADO", "XYZ"},
		{"LCA", "SELIC", "", ErrInvalidIndex, "SELIC", ""},
		{"LCA", "SELIC", "POS", ErrInvalidIndex, "SELIC", "POS"},
		{"LCA", "SELIC", "PRE", ErrInvalidIndex, "SELIC", "PRE"},
		{"LCA", "SELIC", "IPCA", ErrInvalidIndex, "SELIC", "IPCA"},
		{"LCA", "SELIC", "XYZ", ErrInvalidIndex, "SELIC", "XYZ"},
		{"LCA", "IPCA", "", ErrInvalidIndex, "IPCA", ""},
		{"LCA", "IPCA", "POS", ErrInvalidIndex, "IPCA", "POS"},
		{"LCA", "IPCA", "PRE", ErrInvalidIndex, "IPCA", "PRE"},
		{"LCA", "IPCA", "IPCA", ErrInvalidIndex, "IPCA", "IPCA"},
		{"LCA", "IPCA", "XYZ", ErrInvalidIndex, "IPCA", "XYZ"},
		{"LCA", "XYZ", "", ErrInvalidIndex, "XYZ", ""},
		{"LCA", "XYZ", "POS", ErrInvalidIndex, "XYZ", "POS"},
		{"LCA", "XYZ", "PRE", ErrInvalidIndex, "XYZ", "PRE"},
		{"LCA", "XYZ", "IPCA", ErrInvalidIndex, "XYZ", "IPCA"},
		{"LCA", "XYZ", "XYZ", ErrInvalidIndex, "XYZ", "XYZ"},
		{"TESOURO SELIC", "", "", nil, "SELIC", "POS"},
		{"TESOURO SELIC", "", "POS", nil, "SELIC", "POS"},
		{"TESOURO SELIC", "", "PRE", ErrInvalidModality, "SELIC", "PRE"},
		{"TESOURO SELIC", "", "IPCA", ErrInvalidModality, "SELIC", "IPCA"},
		{"TESOURO SELIC", "", "XYZ", ErrInvalidModality, "SELIC", "XYZ"},
		{"TESOURO SELIC", "CDI", "", ErrInvalidIndex, "CDI", ""},
		{"TESOURO SELIC", "CDI", "POS", ErrInvalidIndex, "CDI", "POS"},
		{"TESOURO SELIC", "CDI", "PRE", ErrInvalidIndex, "CDI", "PRE"},
		{"TESOURO SELIC", "CDI", "IPCA", ErrInvalidIndex, "CDI", "IPCA"},
		{"TESOURO SELIC", "CDI", "XYZ", ErrInvalidIndex, "CDI", "XYZ"},
		{"TESOURO SELIC", "PREFIXADO", "", ErrInvalidIndex, "PREFIXADO", ""},
		{"TESOURO SELIC", "PREFIXADO", "POS", ErrInvalidIndex, "PREFIXADO", "POS"},
		{"TESOURO SELIC", "PREFIXADO", "PRE", ErrInvalidIndex, "PREFIXADO", "PRE"},
		{"TESOURO SELIC", "PREFIXADO", "IPCA", ErrInvalidIndex, "PREFIXADO", "IPCA"},
		{"TESOURO SELIC", "PREFIXADO", "XYZ", ErrInvalidIndex, "PREFIXADO", "XYZ"},
		{"TESOURO SELIC", "SELIC", "", nil, "SELIC", "POS"},
		{"TESOURO SELIC", "SELIC", "POS", nil, "SELIC", "POS"},
		{"TESOURO SELIC", "SELIC", "PRE", ErrInvalidModality, "SELIC", "PRE"},
		{"TESOURO SELIC", "SELIC", "IPCA", ErrInvalidModality, "SELIC", "IPCA"},
		{"TESOURO SELIC", "SELIC", "XYZ", ErrInvalidModality, "SELIC", "XYZ"},
		{"TESOURO SELIC", "IPCA", "", ErrInvalidIndex, "IPCA", ""},
		{"TESOURO SELIC", "IPCA", "POS", ErrInvalidIndex, "IPCA", "POS"},
		{"TESOURO SELIC", "IPCA", "PRE", ErrInvalidIndex, "IPCA", "PRE"},
		{"TESOURO SELIC", "IPCA", "IPCA", ErrInvalidIndex, "IPCA", "IPCA"},
		{"TESOURO SELIC", "IPCA", "XYZ", ErrInvalidIndex, "IPCA", "XYZ"},
		{"TESOURO SELIC", "XYZ", "", ErrInvalidIndex, "XYZ", ""},
		{"TESOURO SELIC", "XYZ", "POS", ErrInvalidIndex, "XYZ", "POS"},
		{"TESOURO SELIC", "XYZ", "PRE", ErrInvalidIndex, "XYZ", "PRE"},
		{"TESOURO SELIC", "XYZ", "IPCA", ErrInvalidIndex, "XYZ", "IPCA"},
		{"TESOURO SELIC", "XYZ", "XYZ", ErrInvalidIndex, "XYZ", "XYZ"},
		{"TESOURO PREFIXADO", "", "", nil, "PREFIXADO", "PRE"},
		{"TESOURO PREFIXADO", "", "POS", ErrInvalidModality, "PREFIXADO", "POS"},
		{"TESOURO PREFIXADO", "", "PRE", nil, "PREFIXADO", "PRE"},
		{"TESOURO PREFIXADO", "", "IPCA", ErrInvalidModality, "PREFIXADO", "IPCA"},
		{"TESOURO PREFIXADO", "", "XYZ", ErrInvalidModality, "PREFIXADO", "XYZ"},
		{"TESOURO PREFIXADO", "CDI", "", ErrInvalidIndex, "CDI", ""},
		{"TESOURO PREFIXADO", "CDI", "POS", ErrInvalidIndex, "CDI", "POS"},
		{"TESOURO PREFIXADO", "CDI", "PRE", ErrInvalidIndex, "CDI", "PRE"},
		{"TESOURO PREFIXADO", "CDI", "IPCA", ErrInvalidIndex, "CDI", "IPCA"},
		{"TESOURO PREFIXADO", "CDI", "XYZ", ErrInvalidIndex, "CDI", "XYZ"},
		{"TESOURO PREFIXADO", "PREFIXADO", "", nil, "PREFIXADO", "PRE"},
		{"TESOURO PREFIXADO", "PREFIXADO", "POS", ErrInvalidModality, "PREFIXADO", "POS"},
		{"TESOURO PREFIXADO", "PREFIXADO", "PRE", nil, "PREFIXADO", "PRE"},
		{"TESOURO PREFIXADO", "PREFIXADO", "IPCA", ErrInvalidModality, "PREFIXADO", "IPCA"},
		{"TESOURO PREFIXADO", "PREFIXADO", "XYZ", ErrInvalidModality, "PREFIXADO", "XYZ"},
		{"TESOURO PREFIXADO", "SELIC", "", ErrInvalidIndex, "SELIC", ""},
		{"TESOURO PREFIXADO", "SELIC", "POS", ErrInvalidIndex, "SELIC", "POS"},
		{"TESOURO PREFIXADO", "SELIC", "PRE", ErrInvalidIndex, "SELIC", "PRE"},
		{"TESOURO PREFIXADO", "SELIC", "IPCA", ErrInvalidIndex, "SELIC", "IPCA"},
		{"TESOURO PREFIXADO", "SELIC", "XYZ", ErrInvalidIndex, "SELIC", "XYZ"},
		{"TESOURO PREFIXADO", "IPCA", "", ErrInvalidIndex, "IPCA", ""},
		{"TESOURO PREFIXADO", "IPCA", "POS", ErrInvalidIndex, "IPCA", "POS"},
		{"TESOURO PREFIXADO", "IPCA", "PRE", ErrInvalidIndex, "IPCA", "PRE"},
		{"TESOURO PREFIXADO", "IPCA", "IPCA", ErrInvalidIndex, "IPCA", "IPCA"},
		{"TESOURO PREFIXADO", "IPCA", "XYZ", ErrInvalidIndex, "IPCA", "XYZ"},
		{"TESOURO PREFIXADO", "XYZ", "", ErrInvalidIndex, "XYZ", ""},
		{"TESOURO PREFIXADO", "XYZ", "POS", ErrInvalidIndex, "XYZ", "POS"},
		{"TESOURO PREFIXADO", "XYZ", "PRE", ErrInvalidIndex, "XYZ", "PRE"},
		{"TESOURO PREFIXADO", "XYZ", "IPCA", ErrInvalidIndex, "XYZ", "IPCA"},
		{"TESOURO PREFIXADO", "XYZ", "XYZ", ErrInvalidIndex, "XYZ", "XYZ"},
		{"TESOURO IPCA+", "", "", nil, "IPCA", "IPCA"},
		{"TESOURO IPCA+", "", "POS", ErrInvalidModality, "IPCA", "POS"},
		{"TESOURO IPCA+", "", "PRE", ErrInvalidModality, "IPCA", "PRE"},
		{"TESOURO IPCA+", "", "IPCA", nil, "IPCA", "IPCA"},
		{"TESOURO IPCA+", "", "XYZ", ErrInvalidModality, "IPCA", "XYZ"},
		{"TESOURO IPCA+", "CDI", "", ErrInvalidIndex, "CDI", ""},
		{"TESOURO IPCA+", "CDI", "POS", ErrInvalidIndex, "CDI", "POS"},
		{"TESOURO IPCA+", "CDI", "PRE", ErrInvalidIndex, "CDI", "PRE"},
		{"TESOURO IPCA+", "CDI", "IPCA", ErrInvalidIndex, "CDI", "IPCA"},
		{"TESOURO IPCA+", "CDI", "XYZ", ErrInvalidIndex, "CDI", "XYZ"},
		{"TESOURO IPCA+", "PREFIXADO", "", ErrInvalidIndex, "PREFIXADO", ""},
		{"TESOURO IPCA+", "PREFIXADO", "POS", ErrInvalidIndex, "PREFIXADO", "POS"},
		{"TESOURO IPCA+", "PREFIXADO", "PRE", ErrInvalidIndex, "PREFIXADO", "PRE"},
		{"TESOURO IPCA+", "PREFIXADO", "IPCA", ErrInvalidIndex, "PREFIXADO", "IPCA"},
		{"TESOURO IPCA+", "PREFIXADO", "XYZ", ErrInvalidIndex, "PREFIXADO", "XYZ"},
		{"TESOURO IPCA+", "SELIC", "", ErrInvalidIndex, "SELIC", ""},
		{"TESOURO IPCA+", "SELIC", "POS", ErrInvalidIndex, "SELIC", "POS"},
		{"TESOURO IPCA+", "SELIC", "PRE", ErrInvalidIndex, "SELIC", "PRE"},
		{"TESOURO IPCA+", "SELIC", "IPCA", ErrInvalidIndex, "SELIC", "IPCA"},
		{"TESOURO IPCA+", "SELIC", "XYZ", ErrInvalidIndex, "SELIC", "XYZ"},
		{"TESOURO IPCA+", "IPCA", "", nil, "IPCA", "IPCA"},
		{"TESOURO IPCA+", "IPCA", "POS", ErrInvalidModality, "IPCA", "POS"},
		{"TESOURO IPCA+", "IPCA", "PRE", ErrInvalidModality, "IPCA", "PRE"},
		{"TESOURO IPCA+", "IPCA", "IPCA", nil, "IPCA", "IPCA"},
		{"TESOURO IPCA+", "IPCA", "XYZ", ErrInvalidModality, "IPCA", "XYZ"},
		{"TESOURO IPCA+", "XYZ", "", ErrInvalidIndex, "XYZ", ""},
		{"TESOURO IPCA+", "XYZ", "POS", ErrInvalidIndex, "XYZ", "POS"},
		{"TESOURO IPCA+", "XYZ", "PRE", ErrInvalidIndex, "XYZ", "PRE"},
		{"TESOURO IPCA+", "XYZ", "IPCA", ErrInvalidIndex, "XYZ", "IPCA"},
		{"TESOURO IPCA+", "XYZ", "XYZ", ErrInvalidIndex, "XYZ", "XYZ"},
		{"CRI", "", "", ErrUnsupportedType, "", ""},
		{"CRI", "", "POS", ErrUnsupportedType, "", "POS"},
		{"CRI", "", "PRE", ErrUnsupportedType, "", "PRE"},
		{"CRI", "", "IPCA", ErrUnsupportedType, "", "IPCA"},
		{"CRI", "", "XYZ", ErrUnsupportedType, "", "XYZ"},
		{"CRI", "CDI", "", ErrUnsupportedType, "CDI", ""},
		{"CRI", "CDI", "POS", ErrUnsupportedType, "CDI", "POS"},
		{"CRI", "CDI", "PRE", ErrUnsupportedType, "CDI", "PRE"},
		{"CRI", "CDI", "IPCA", ErrUnsupportedType, "CDI", "IPCA"},
		{"CRI", "CDI", "XYZ", ErrUnsupportedType, "CDI", "XYZ"},
		{"CRI", "PREFIXADO", "", ErrUnsupportedType, "PREFIXADO", ""},
		{"CRI", "PREFIXADO", "POS", ErrUnsupportedType, "PREFIXADO", "POS"},
		{"CRI", "PREFIXADO", "PRE", ErrUnsupportedType, "PREFIXADO", "PRE"},
		{"CRI", "PREFIXADO", "IPCA", ErrUnsupportedType, "PREFIXADO", "IPCA"},
		{"CRI", "PREFIXADO", "XYZ", ErrUnsupportedType, "PREFIXADO", "XYZ"},
		{"CRI", "SELIC", "", ErrUnsupportedType, "SELIC", ""},
		{"CRI", "SELIC", "POS", ErrUnsupportedType, "SELIC", "POS"},
		{"CRI", "SELIC", "PRE", ErrUnsupportedType, "SELIC", "PRE"},
		{"CRI", "SELIC", "IPCA", ErrUnsupportedType, "SELIC", "IPCA"},
		{"CRI", "SELIC", "XYZ", ErrUnsupportedType, "SELIC", "XYZ"},
		{"CRI", "IPCA", "", ErrUnsupportedType, "IPCA", ""},
		{"CRI", "IPCA", "POS", ErrUnsupportedType, "IPCA", "POS"},
		{"CRI", "IPCA", "PRE", ErrUnsupportedType, "IPCA", "PRE"},
		{"CRI", "IPCA", "IPCA", ErrUnsupportedType, "IPCA", "IPCA"},
		{"CRI", "IPCA", "XYZ", ErrUnsupportedType, "IPCA", "XYZ"},
		{"CRI", "XYZ", "", ErrUnsupportedType, "XYZ", ""},
		{"CRI", "XYZ", "POS", ErrUnsupportedType, "XYZ", "POS"},
		{"CRI", "XYZ", "PRE", ErrUnsupportedType, "XYZ", "PRE"},
		{"CRI", "XYZ", "IPCA", ErrUnsupportedType, "XYZ", "IPCA"},
		{"CRI", "XYZ", "XYZ", ErrUnsupportedType, "XYZ", "XYZ"},
		{"", "", "", ErrTypeRequired, "", ""},
		{"", "", "POS", ErrTypeRequired, "", "POS"},
		{"", "", "PRE", ErrTypeRequired, "", "PRE"},
		{"", "", "IPCA", ErrTypeRequired, "", "IPCA"},
		{"", "", "XYZ", ErrTypeRequired, "", "XYZ"},
		{"", "CDI", "", ErrTypeRequired, "CDI", ""},
		{"", "CDI", "POS", ErrTypeRequired, "CDI", "POS"},
		{"", "CDI", "PRE", ErrTypeRequired, "CDI", "PRE"},
		{"", "CDI", "IPCA", ErrTypeRequired, "CDI", "IPCA"},
		{"", "CDI", "XYZ", ErrTypeRequired, "CDI", "XYZ"},
		{"", "PREFIXADO", "", ErrTypeRequired, "PREFIXADO", ""},
		{"", "PREFIXADO", "POS", ErrTypeRequired, "PREFIXADO", "POS"},
		{"", "PREFIXADO", "PRE", ErrTypeRequired, "PREFIXADO", "PRE"},
		{"", "PREFIXADO", "IPCA", ErrTypeRequired, "PREFIXADO", "IPCA"},
		{"", "PREFIXADO", "XYZ", ErrTypeRequired, "PREFIXADO", "XYZ"},
		{"", "SELIC", "", ErrTypeRequired, "SELIC", ""},
		{"", "SELIC", "POS", ErrTypeRequired, "SELIC", "POS"},
		{"", "SELIC", "PRE", ErrTypeRequired, "SELIC", "PRE"},
		{"", "SELIC", "IPCA", ErrTypeRequired, "SELIC", "IPCA"},
		{"", "SELIC", "XYZ", ErrTypeRequired, "SELIC", "XYZ"},
		{"", "IPCA", "", ErrTypeRequired, "IPCA", ""},
		{"", "IPCA", "POS", ErrTypeRequired, "IPCA", "POS"},
		{"", "IPCA", "PRE", ErrTypeRequired, "IPCA", "PRE"},
		{"", "IPCA", "IPCA", ErrTypeRequired, "IPCA", "IPCA"},
		{"", "IPCA", "XYZ", ErrTypeRequired, "IPCA", "XYZ"},
		{"", "XYZ", "", ErrTypeRequired, "XYZ", ""},
		{"", "XYZ", "POS", ErrTypeRequired, "XYZ", "POS"},
		{"", "XYZ", "PRE", ErrTypeRequired, "XYZ", "PRE"},
		{"", "XYZ", "IPCA", ErrTypeRequired, "XYZ", "IPCA"},
		{"", "XYZ", "XYZ", ErrTypeRequired, "XYZ", "XYZ"},
	}

	for _, c := range casos {
		req := AnalyzeInvestmentRequest{Type: c.tipo, Rate: 10, Index: c.index, Modality: c.modalidade}
		req.Normalize()

		erro := req.Validate()

		if !errors.Is(erro, c.erro) {
			t.Errorf("Validate(tipo=%q index=%q modalidade=%q): erro esperado %v, obtido %v",
				c.tipo, c.index, c.modalidade, c.erro, erro)
			continue
		}
		if req.Index != c.indexFinal || req.Modality != c.modalidadeFinal {
			t.Errorf("Validate(tipo=%q index=%q modalidade=%q): esperado index=%q modalidade=%q, obtido index=%q modalidade=%q",
				c.tipo, c.index, c.modalidade, c.indexFinal, c.modalidadeFinal, req.Index, req.Modality)
		}
	}
}
